// Configuración de Supabase
const SUPABASE_URL = 'https://vgnxioxzwhunaktthimb.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbnhpb3h6d2h1bmFrdHRoaW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4NTU3OTUsImV4cCI6MjEwNDQzMTc5NX0.rGQpKJpBzTHnGvcvkMFLk6fkFGoX0qRlVpZjllYhuCg';
